# -*- coding: utf-8 -*-
"""Dziadekmroz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReLXa71rJAXHMwClKvWOrAKIYpoPAHgl
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

def rysuj_mikolaja_jasna_skora_i_tlem():
    """Generuje figurę Matplotlib przedstawiającą Mikołaja."""

    # 1. Konfiguracja "płótna" (figura jest zwracana, zamiast tylko wyświetlana)
    fig, ax = plt.subplots(figsize=(7, 9))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 13)
    ax.set_aspect('equal')
    ax.axis('off')

    # --- TŁO ---
    SKY_BLUE = '#87CEEB' # Jasny błękitny kolor
    ax.add_patch(patches.Rectangle((0, 0), 10, 13, color=SKY_BLUE))

    # Kolory (stałe)
    RED = '#D32F2F'
    SKIN = '#FFE0BD'  # Jasna, cielista skóra
    GOLD = '#FFD700'
    GLOVE_GREEN = '#2E8B57'
    BOX_BLUE = '#1E90FF'

    # --- NOGI I BUTY (Rozdzielone) ---
    noga_lewa = patches.Rectangle((4.0, 0.5), 0.8, 3.5, color=RED)
    noga_prawa = patches.Rectangle((5.2, 0.5), 0.8, 3.5, color=RED)
    ax.add_patch(noga_lewa)
    ax.add_patch(noga_prawa)

    but_lewy = patches.Rectangle((3.8, 0), 1.2, 0.8, color='black')
    but_prawy = patches.Rectangle((5.0, 0), 1.2, 0.8, color='black')
    ax.add_patch(but_lewy)
    ax.add_patch(but_prawy)

    mankiet_l = patches.Rectangle((3.9, 0.8), 1.0, 0.3, color='white')
    mankiet_p = patches.Rectangle((5.1, 0.8), 1.0, 0.3, color='white')
    ax.add_patch(mankiet_l)
    ax.add_patch(mankiet_p)

    # --- TUŁÓW (Warstwa środkowa) ---
    tulow = patches.Ellipse((5, 4.0), width=6.0, height=5.5, color=RED)
    ax.add_patch(tulow)

    ax.add_patch(patches.Circle((5, 5.0), 0.2, color='white'))
    ax.add_patch(patches.Circle((5, 4.0), 0.2, color='white'))

    pas = patches.Rectangle((2.0, 2.8), 6.0, 0.8, color='black')
    ax.add_patch(pas)

    klamra = patches.Rectangle((4.5, 2.7), 1, 1, color=GOLD, fill=False, linewidth=3)
    ax.add_patch(klamra)
    ax.add_patch(patches.Rectangle((4.9, 2.8), 0.2, 0.8, color=GOLD))


    # --- RĘCE I PREZENT (Warstwa przednia) ---
    rekaw_l = patches.Ellipse((7.8, 4.8), 2.5, 1.3, angle=-30, color=RED)
    ax.add_patch(rekaw_l)
    mankiet_l = patches.Circle((8.7, 4.2), 0.6, color='white')
    ax.add_patch(mankiet_l)
    rekawica_l = patches.Circle((9.0, 4.0), 0.5, color=GLOVE_GREEN)
    ax.add_patch(rekawica_l)

    rekaw_p = patches.Ellipse((2.2, 4.8), 2.5, 1.3, angle=30, color=RED)
    ax.add_patch(rekaw_p)
    mankiet_p = patches.Circle((1.3, 4.2), 0.6, color='white')
    ax.add_patch(mankiet_p)
    rekawica_p = patches.Circle((1.0, 4.5), 0.5, color=GLOVE_GREEN)
    ax.add_patch(rekawica_p)

    # PREZENT
    box_x, box_y = 0.3, 4.8
    box_w, box_h = 1.8, 1.8
    pudelko = patches.Rectangle((box_x, box_y), box_w, box_h, color=BOX_BLUE)
    ax.add_patch(pudelko)

    wstazka_pion = patches.Rectangle((box_x + box_w/2 - 0.15, box_y), 0.3, box_h, color=GOLD)
    wstazka_poziom = patches.Rectangle((box_x, box_y + box_h/2 - 0.15), box_w, 0.3, color=GOLD)
    ax.add_patch(wstazka_pion)
    ax.add_patch(wstazka_poziom)

    kokarda_lewa = patches.Ellipse((box_x + box_w/2 - 0.4, box_y + box_h + 0.1), 0.8, 0.4, angle=30, color=GOLD)
    kokarda_prawa = patches.Ellipse((box_x + box_w/2 + 0.4, box_y + box_h + 0.1), 0.8, 0.4, angle=-30, color=GOLD)
    ax.add_patch(kokarda_lewa)
    ax.add_patch(kokarda_prawa)
    ax.add_patch(patches.Circle((box_x + box_w/2, box_y + box_h), 0.2, color=GOLD))


    # --- GŁOWA, TWARZ, CZAPKA ---
    glowa = patches.Circle((5, 7.5), 1.3, color=SKIN)
    ax.add_patch(glowa)

    wspolrzedne_brody = [(3.8, 7.0), (4.2, 6.7), (4.6, 6.5), (5.0, 6.4),
                         (5.4, 6.5), (5.8, 6.7), (6.2, 7.0),
                         (4.2, 6.3), (5.0, 6.0), (5.8, 6.3)]
    for x, y in wspolrzedne_brody:
        ax.add_patch(patches.Circle((x, y), 0.45, color='white'))

    was_lewy = patches.Ellipse((4.5, 7.3), 1.2, 0.5, angle=20, color='white')
    was_prawy = patches.Ellipse((5.5, 7.3), 1.2, 0.5, angle=-20, color='white')
    ax.add_patch(was_lewy)
    ax.add_patch(was_prawy)

    oko_lewe = patches.Circle((4.6, 7.8), 0.12, color='black')
    oko_prawe = patches.Circle((5.4, 7.8), 0.12, color='black')
    ax.add_patch(oko_lewe)
    ax.add_patch(oko_prawe)

    nos = patches.Circle((5, 7.5), 0.2, color='#F08080')
    ax.add_patch(nos)

    czapka_trojkat = patches.Polygon([[3.6, 8.3], [6.4, 8.3], [5, 11.0]], color=RED)
    ax.add_patch(czapka_trojkat)
    otok = patches.FancyBboxPatch((3.5, 8.1), 3, 0.6, boxstyle="round,pad=0.1", color='white')
    ax.add_patch(otok)
    pompon = patches.Circle((5, 11.0), 0.4, color='white')
    ax.add_patch(pompon)


    plt.title("Wesołych Świąt! Mikołaj z Prezentem i Błękitnym Tłem", fontsize=16, color='darkred')

    # Zwrócenie obiektu figury zamiast wyświetlania go
    return fig

# --- GŁÓWNA FUNKCJA STREAMLIT ---
def main():
    st.set_page_config(page_title="Mikołaj Matplotlib", layout="centered")
    st.title("🎅 Generowanie Mikołaja w Streamlit")
    st.write("Rysunek Świętego Mikołaja wygenerowany przy użyciu biblioteki Matplotlib i wyświetlony przez Streamlit.")

    if st.button("Generuj Mikołaja!"):
        # Wywołanie funkcji rysującej i przekazanie jej do Streamlit
        figura_mikolaja = rysuj_mikolaja_jasna_skora_i_tlem()
        st.pyplot(figura_mikolaja)
        st.success("Rysunek wygenerowany pomyślnie!")

    # Przycisk opcjonalny
    st.markdown("---")
    st.info("Aby uruchomić aplikację, zapisz kod jako `app.py` i uruchom w terminalu komendą: `streamlit run app.py`")

if __name__ == "__main__":
    # Uruchomienie aplikacji Streamlit
    main()